import { useState } from 'react';
import { useSearchParams, useNavigate, Link } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';
import { CheckCircle2, AlertTriangle, Dumbbell, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { apiErrorMessage } from '@/lib/api-error';
import api from '@services/api';

interface TokenPreview {
  valid: boolean;
  memberName: string;
  gymName: string;
  memberCode?: string;
}

/**
 * Public activation page for member onboarding.
 * The member arrives here via a one-time secure link generated by gym staff.
 * Pre-validates the token via GET /auth/activate/:token and allows the member
 * to set their own password securely.
 */
export function ClaimAccountPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [token, setToken] = useState(searchParams.get('token') ?? '');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [done, setDone] = useState(false);

  const cleanToken = token.trim();

  // Pre-validate token on mount if present in URL
  const {
    data: preview,
    isLoading: isValidating,
    isError: isTokenInvalid,
    error: tokenError,
  } = useQuery<TokenPreview>({
    queryKey: ['validate-activation', cleanToken],
    queryFn: async () => {
      const res: any = await api.get(`/auth/activate/${encodeURIComponent(cleanToken)}`);
      return res?.data?.data ?? res?.data;
    },
    enabled: cleanToken.length >= 10,
    retry: false,
  });

  const activateMutation = useMutation({
    mutationFn: () => api.post('/auth/activate', { token: cleanToken, password }),
    onSuccess: () => setDone(true),
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (cleanToken.length < 10) return;
    if (password.length < 8) return;
    if (password !== confirmPassword) return;
    activateMutation.mutate();
  };

  if (done) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4 bg-background">
        <Card className="max-w-sm w-full">
          <CardContent className="pt-6 text-center space-y-3">
            <CheckCircle2 className="h-12 w-12 text-green-600 mx-auto" />
            <h1 className="text-xl font-semibold tracking-tight">Account Activated!</h1>
            <p className="text-sm text-muted-foreground">
              Your member login is now active. You can now log in and access your member dashboard.
            </p>
            <Button className="w-full mt-2" onClick={() => navigate('/login')}>
              Go to login
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (cleanToken.length >= 10 && isTokenInvalid) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4 bg-background">
        <Card className="max-w-sm w-full">
          <CardContent className="pt-6 text-center space-y-4">
            <ShieldAlert className="h-12 w-12 text-destructive mx-auto" />
            <h1 className="text-lg font-semibold tracking-tight">Unable to Activate</h1>
            <div className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive text-left">
              {apiErrorMessage(tokenError)}
            </div>
            <p className="text-xs text-muted-foreground">
              If your link has expired or was already used, please contact your gym reception to receive a new invitation link.
            </p>
            <Button className="w-full" onClick={() => navigate('/login')}>
              Back to Login
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-background">
      <Card className="max-w-sm w-full">
        <CardHeader className="text-center pb-2">
          <div className="mx-auto h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center mb-2">
            <Dumbbell className="h-6 w-6 text-primary" />
          </div>
          <CardTitle className="text-xl font-bold">Activate Member Account</CardTitle>
          <p className="text-xs text-muted-foreground">
            Set your password to activate your MuscleOS account.
          </p>
        </CardHeader>
        <CardContent>
          {isValidating && (
            <div className="py-4 text-center text-sm text-muted-foreground animate-pulse">
              Verifying activation link...
            </div>
          )}

          {preview && (
            <div className="rounded-lg bg-primary/5 p-3 space-y-1 text-sm border border-primary/10 mb-4">
              <div className="flex justify-between items-center">
                <span className="text-xs text-muted-foreground">Member:</span>
                <span className="font-semibold text-foreground">{preview.memberName}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-xs text-muted-foreground">Gym:</span>
                <span className="font-semibold text-foreground">{preview.gymName}</span>
              </div>
              {preview.memberCode && (
                <div className="flex justify-between items-center">
                  <span className="text-xs text-muted-foreground">Member Code:</span>
                  <span className="font-mono text-xs text-muted-foreground">{preview.memberCode}</span>
                </div>
              )}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            {!searchParams.get('token') && (
              <div>
                <Label htmlFor="token">Activation Code</Label>
                <Input
                  id="token"
                  value={token}
                  onChange={(e) => setToken(e.target.value)}
                  placeholder="Paste code from your gym"
                  required
                />
              </div>
            )}
            <div>
              <Label htmlFor="password">Create Password</Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="At least 8 characters"
                minLength={8}
                required
              />
            </div>
            <div>
              <Label htmlFor="confirmPassword">Confirm Password</Label>
              <Input
                id="confirmPassword"
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                placeholder="Confirm chosen password"
                minLength={8}
                required
              />
            </div>
            {password && confirmPassword && password !== confirmPassword && (
              <p className="text-xs text-destructive">Passwords do not match.</p>
            )}
            {activateMutation.isError && (
              <div className="flex items-center gap-2 text-sm text-destructive rounded bg-destructive/10 p-2">
                <AlertTriangle className="h-4 w-4 shrink-0" />
                <span>{apiErrorMessage(activateMutation.error)}</span>
              </div>
            )}
            <Button
              type="submit"
              className="w-full"
              disabled={
                activateMutation.isPending ||
                cleanToken.length < 10 ||
                password.length < 8 ||
                password !== confirmPassword
              }
            >
              {activateMutation.isPending ? 'Activating...' : 'Activate Account'}
            </Button>
            <p className="text-center text-xs text-muted-foreground">
              Already activated?{' '}
              <Link to="/login" className="text-primary font-medium hover:underline">
                Sign in
              </Link>
            </p>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
